# WHO BROKE THE RACK
# Server #4 PXE Proxy DHCP configuration

port=0
interface=bond0
bind-interfaces
log-dhcp

dhcp-range=192.168.100.0,proxy,255.255.255.0

dhcp-host=70:10:6f:a1:aa:41,set:server4
dhcp-ignore=tag:!known

pxe-prompt=tag:server4,"Rocky Linux 9 PXE",0
pxe-service=tag:server4,x86PC,"Rocky Linux 9",pxelinux,192.168.100.60
